### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by antielvis** [OpenNebula/addon-3par#1]
Hello! 
Installed on OpenNebula 6.0.0.2.
There is no 3PAR storage type. 
![изображение_2023-10-12_165015234](https://github.com/OpenNebula/addon-3par/assets/17472041/229581c6-7b65-4c2a-a8c4-905260031b54)

Then I created the script manually:
NAME = "3PAR IMAGE"
DS_MAD = "3par"
TM_MAD = "3par"
TYPE = "IMAGE_DS"
DISK_TYPE = "block"
CPG = "FC_r1_1_1"
NAMING_TYPE = "tst"
BRIDGE_LIST = "srv02.a.local"
QOS_ENABLE = "YES"

The section does not see it: onedatastore list
  ID NAME                     SIZE AVA  CLUSTERS IMAGES TYPE DS      TM      STAT
 106 3PAR IMAGE            0M -               0               0     img  3par    3par    on

![изображение_2023-10-12_165210435](https://github.com/OpenNebula/addon-3par/assets/17472041/17a25aaa-f141-4a3f-a9d0-c92f7844012d)

**Comment by feldsam** [comment]
Hello @antielvis , integration with sunstone is not open-source. You can order support package from us to get it.


Are you configured IP, username and password correctly in conf file?
